repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: database.md
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
  - repo: local
    hooks:
      - id: api-schema
        name: renew api docs
        entry: task api
        language: system
        pass_filenames: false
      - id: migration-check
        name: check for missing migrations
        entry: task migrations
        language: system
        pass_filenames: false
      - id: lint
        name: lint BE + FE
        entry: task lint
        language: system
        pass_filenames: false
