x-service: &service
  build:
    dockerfile: ./docker/backend/Dockerfile
    context: ./
  env_file:
    - .env
  image: ${COMPOSE_PROJECT_NAME}/backend-${ENVIRONMENT}
  volumes:
    - static:/code/static/
    - attachments:/code/attachments/
services:
  api:
    <<: *service
    container_name: ${COMPOSE_PROJECT_NAME}-api-${ENVIRONMENT}
    command:
      - prod
  celery:
    extends:
      file: compose.yml
      service: celery
  caddy:
    extends:
      file: compose.yml
      service: caddy
  cache:
    extends:
      file: compose.yml
      service: cache
  docs:
    extends:
      file: compose.yml
      service: docs
  frontend:
    extends:
      file: compose.yml
      service: frontend
volumes:
  static:
  attachments:
  caddy_data:
  caddy_config:
  docs:
  cache_data:
  frontend_data:
