x-service: &service
  build:
    dockerfile: ./docker/backend/Dockerfile
    context: ./
  env_file:
    - .env
  image: ${COMPOSE_PROJECT_NAME}/backend-${ENVIRONMENT}
  volumes:
    - static:/code/static/
    - attachments:/code/attachments/
services:
  api:
    <<: *service
    container_name: ${COMPOSE_PROJECT_NAME}-api-${ENVIRONMENT}
    command:
      - prod
  celery:
    <<: *service
    depends_on:
      - redis
    command: celery worker -l INFO -Q django
  caddy:
    container_name: ${COMPOSE_PROJECT_NAME}-caddy-${ENVIRONMENT}
    build:
      dockerfile: ./docker/caddy/Dockerfile
      context: ./
    env_file:
      - .env
    ports:
      - "${SERVICE_PORT}:80"
    volumes:
      - static:/static
      - attachments:/attachments
      - docs:/docs
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - api
  redis:
    image: redis:7.2.5
    volumes:
      - redis_data:/data

  docs:
    build:
      dockerfile: ./docker/docs/Dockerfile
      context: ./
    env_file:
      - .env
    image: ${COMPOSE_PROJECT_NAME}/docs
    container_name: ${COMPOSE_PROJECT_NAME}-docs-${ENVIRONMENT}
    command:
      - build
    volumes:
      - ./docs:/code/docs
      - docs:/code/doc_site
volumes:
  static:
  attachments:
  docs:
  redis_data:
