x-service: &service
  build:
    dockerfile: ./docker/backend/Dockerfile
    context: ./
  env_file:
    - .env
  image: ${COMPOSE_PROJECT_NAME}/backend-${ENVIRONMENT}
services:
  api:
    <<: *service
    container_name: ${COMPOSE_PROJECT_NAME}-api-${ENVIRONMENT}
    command:
      - prod
    image: ${COMPOSE_PROJECT_NAME}/backend-${ENVIRONMENT}
    volumes:
      - attachments:/code/attachments/
  celery:
    <<: *service
    depends_on:
      - redis
    command: celery worker -l INFO -Q django
  caddy:
    container_name: ${COMPOSE_PROJECT_NAME}-caddy-${ENVIRONMENT}
    build:
      dockerfile: ./docker/caddy/Dockerfile
      context: ./
    env_file:
    - .env
    ports:
      - "${SERVICE_PORT}:80"
    volumes:
      - static:/static
      - attachments:/attachments
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - api
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
volumes:
  static:
  attachments:
  redis_data:
