services:
  docs:
    extends:
      file: compose.yml
      service: docs
    ports:
      - "2000:2000"
    command:
      - serve
  db:
    extends:
      file: compose.yml
      service: db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    extends:
      file: compose.yml
      service: redis
    ports:
      - "6379:6379"
volumes:
  postgres_data:
  redis_data:
  docs:
