version: "3"
dotenv: [".env"]
tasks:
  manage:
    desc: "Run Django management commands"
    dir: backend
    cmds:
      - uv run python manage.py {{.CLI_ARGS}}
  deploy:
    desc: "Deploy on production"
    cmds:
      - git pull
      - docker compose down
      - docker compose build
      - docker compose up -d
      - docker system prune -f
  install:
    desc: Install Frontend and Backend dependencies
    deps:
      - install.be
      - install.fe
  install.be:
    dir: backend
    cmds:
      - uv sync --all-groups
    silent: true
  install.fe:
    dir: frontend
    cmds:
      - yarn install
    silent: true
  update:
    desc: "Update dependencies"
    deps:
      - update.be
      - update.fe
    silent: true
  update.be:
    dir: backend
    cmds:
      - uv lock --upgrade
    silent: true
  update.fe:
    dir: frontend
    cmds:
      - yarn upgrade-interactive
  up.dev:
    desc: "Start dev dependencies"
    cmds:
      - docker compose -f compose.dev.yml --env-file .env up cache db docs -d
    silent: true
  backup.db:
    cmds:
      - docker exec -t ${COMPOSE_PROJECT_NAME}-db-${ENVIRONMENT} pg_dump -c -U ${POSTGRES_USER} > $HOME/backups/dump_`date +%Y-%m-%d"_"%H`.sql
  restore.db:
    - cat  $HOME/backups/{{.CLI_ARGS}} | docker exec -i ${COMPOSE_PROJECT_NAME}-db-${ENVIRONMENT} psql -U ${POSTGRES_USER}
  backup.files:
    cmds:
      - docker run --rm --volumes-from ${COMPOSE_PROJECT_NAME}-api-${ENVIRONMENT}  -v $HOME/backups:/backup ${COMPOSE_PROJECT_NAME}/backend-${ENVIRONMENT} bash -c "tar cvf /backup/backup_$(date +%Y%m%d%H).tar /code/attachments/";
  restore.files:
    cmds:
      - docker run --rm --volumes-from ${COMPOSE_PROJECT_NAME}-api-${ENVIRONMENT} -v $HOME/backups:/backup ${COMPOSE_PROJECT_NAME}/backend-${ENVIRONMENT} bash -c "cd /code/attachments/ && tar xvf /backup/{{.CLI_ARGS}} --strip 1"
  down.dev:
    cmds:
      - docker compose -f compose.dev.yml --env-file .env down --remove-orphans
    silent: true
  shell:
    dir: backend
    cmds:
      - uv run python manage.py shell_plus
    silent: true
  migrations:
    dir: backend
    cmds:
      - uv run python manage.py makemigrations
    silent: true
  api:
    desc: Generate API specification from BE and generate client for FE
    cmds:
      - task api.be
      - task api.fe
  api.be:
    dir: backend
    cmds:
      - uv run python manage.py spectacular --color --file ../docs/schema.yml
  api.fe:
    dir: frontend
    cmds:
      - yarn run api
  coverage:
    dir: backend
    cmds:
      - uv run coverage run manage.py test -b
      - uv run coverage report -m
    silent: true
  erd:
    dir: backend
    cmds:
      - uv run python manage.py graph_models -a   -o ../docs/database/database.dot
      - mv ../docs/database/database.dot ../docs/database/database.md
      - sed -i '' '1s/^/```graphviz dot erd.png\n/' ../docs/database/database.md && echo '```' >> ../docs/database/database.md
      - "sed -i '' '/^ *.. Created: .*/d' ../docs/database/database.md"
    silent: true
  urls:
    dir: backend
    cmds:
      - uv run python manage.py show_urls --format=pretty-json > ../docs/urls.json
    silent: true
  lint:
    desc: Run frontend and backend linters
    deps:
      - lint.be
      - lint.fe
  lint.be:
    dir: backend
    cmds:
      - uv run ruff check . --fix && uv run ruff  format
    silent: true
  lint.fe:
    dir: frontend
    cmds:
      - yarn run lint
  release:
    desc: Create GitHub release using calver and daily index
    cmds:
      - |
        #!/bin/bash
        set -e

        DATE=$(date +'%Y.%m.%d')
        PREFIX="v$DATE"

        echo "Looking for existing tags starting with $PREFIX..."

        TAGS=$(gh release list --limit 100 --json tagName -q '.[].tagName' | grep "^$PREFIX\\." || true)

        MAX_INDEX=0
        for TAG in $TAGS; do
          SUFFIX="${TAG##$PREFIX.}" # extract after the last dot
          if [[ "$SUFFIX" =~ ^[0-9]+$ ]] && (( SUFFIX > MAX_INDEX )); then
            MAX_INDEX=$SUFFIX
          fi
        done

        NEW_INDEX=$((MAX_INDEX + 1))
        NEW_TAG="$PREFIX.$NEW_INDEX"

        echo "Latest tag: $PREFIX.$MAX_INDEX"
        echo "Creating new tag: $NEW_TAG"
        gh release create "$NEW_TAG" --generate-notes --target staging
    silent: false
  changelog:
    desc: Generate changelog from git history
    cmds:
      - git cliff -o CHANGELOG.md
    silent: true
  release-notes:
    desc: Generate release notes from git history
    cmds:
      - |
        #!/bin/bash
        set -e

        DATE=$(date +'%Y.%m.%d')
        PREFIX="v$DATE"
        echo "Looking for existing tags starting with $PREFIX..."
        TAGS=$(gh release list --limit 100 --json tagName -q '.[].tagName' | grep "^$PREFIX\\." || true)
        MAX_INDEX=0
        for TAG in $TAGS; do
          SUFFIX="${TAG##$PREFIX.}" # extract after the last dot
          if [[ "$SUFFIX" =~ ^[0-9]+$ ]] && (( SUFFIX > MAX_INDEX )); then
            MAX_INDEX=$SUFFIX
          fi
        done

        NEW_INDEX=$((MAX_INDEX + 1))
        NEW_TAG="$PREFIX.$NEW_INDEX"
        echo "Latest tag: $PREFIX.$MAX_INDEX"
        gh release edit $PREFIX.$MAX_INDEX --notes-file CHANGELOG.md
    silent: true
