version: "3"
env:
  COMPOSE_PROJECT_NAME: loyalist
dotenv: [".env"]
tasks:
  manage:
    desc: "Run Django management commands"
    dir: backend
    cmds:
      - uv run python manage.py {{.CLI_ARGS}}
  deploy:
    desc: "Deploy on production"
    cmds:
      - git pull
      - docker compose -f compose.slim.yml  down --remove-orphans
      - docker compose -f compose.slim.yml  build
      - docker compose -f compose.slim.yml  up -d

  getdb:
    cmds:
      - docker compose exec db hostname -i
  install:
    desc: Install Frontend and Backend dependencies
    deps:
      - install.be
      - install.fe
  install.be:
    dir: backend
    cmds:
      - uv sync --all-extras
    silent: true
  install.fe:
    dir: frontend
    cmds:
      - yarn install
    silent: true
  update:
    desc: "Update dependencies"
    deps:
      - update.be
      - update.fe
    silent: true
  update.be:
    dir: backend
    cmds:
      - uv lock --upgrade
    silent: true
  update.fe:
    dir: frontend
    cmds:
      - yarn upgrade-interactive
  up.dev:
    desc: "Start dev dependencies"
    cmds:
      - docker compose -f compose.dev.yml --env-file .env up cache db docs -d
    silent: true
  backup.db:
    cmds:
      - docker exec -t ${COMPOSE_PROJECT_NAME}-db-${ENVIRONMENT} pg_dump -c -U ${POSTGRES_USER} > $HOME/backups/dump_`date +%Y-%m-%d"_"%H`.sql
  restore.db:
    - cat  $HOME/backups/{{.CLI_ARGS}} | docker exec -i ${COMPOSE_PROJECT_NAME}-db-${ENVIRONMENT} psql -U ${POSTGRES_USER}
  backup.files:
    cmds:
      - docker run --rm --volumes-from ${COMPOSE_PROJECT_NAME}-api-${ENVIRONMENT}  -v $HOME/backups:/backup ${COMPOSE_PROJECT_NAME}/backend-${ENVIRONMENT} bash -c "tar cvf /backup/backup_$(date +%Y%m%d%H).tar /code/attachments/";
  restore.files:
    cmds:
      - docker run --rm --volumes-from ${COMPOSE_PROJECT_NAME}-api-${ENVIRONMENT} -v $HOME/backups:/backup ${COMPOSE_PROJECT_NAME}/backend-${ENVIRONMENT} bash -c "cd /code/attachments/ && tar xvf /backup/{{.CLI_ARGS}} --strip 1"
  down.dev:
    cmds:
      - docker compose -f compose.dev.yml --env-file .env down --remove-orphans
    silent: true
  local.shell:
    dir: backend
    cmds:
      - uv run python manage.py shell_plus
    silent: true
  migrations:
    dir: backend
    cmds:
      - uv run python manage.py makemigrations
    silent: true
  api:
    desc: Generate API specification from BE and generate client for FE
    cmds:
      - task api.be
      - task api.fe
  api.be:
    dir: backend
    cmds:
      - uv run python manage.py spectacular --color --file ../docs/schema.yml
  api.fe:
    dir: frontend
    cmds:
      - yarn run api
  coverage:
    dir: backend
    cmds:
      - uv run python coverage run manage.py test
      - uv run python coverage report -m
    silent: true
  erd:
    dir: backend
    cmds:
      - uv run python manage.py graph_models -a   -o ../docs/database/database.dot
      - mv ../docs/database/database.dot ../docs/database/database.md
      - sed -i '' '1s/^/```graphviz dot erd.png\n/' ../docs/database/database.md && echo '```' >> ../docs/database/database.md
      - "sed -i '' '/^ *.. Created: .*/d' ../docs/database/database.md"
    silent: true
  lint:
    desc: Run frontend and backend linters
    deps:
      - lint.be
      - lint.fe
  lint.be:
    dir: backend
    cmds:
      - uv run ruff check . --fix && uv run ruff  format
    silent: true
  lint.fe:
    dir: frontend
    cmds:
      - yarn run lint
  dev.init:
    ignore_error: true
    dir: backend
    cmds:
      - uv run python manage.py createsuperuser --no-input
    silent: true
  dev.dump_initial:
    dir: backend
    cmds:
      - uv run python manage.py dumpdata support.Country support.TransportMode support.Incoterm support.ServiceType support.PaymentTerm support.PackagingType support.DocumentType support.Container --indent 2 > support/fixtures/initial_data.json
    silent: true
  greenmask.dump:
    cmds:
      - docker compose -f compose.yml run --rm greenmask dump --config /var/lib/workdir/config.yaml
  greenmask.list:
    cmds:
      - docker compose -f compose.yml run --rm greenmask list-dumps --config /var/lib/workdir/config.yaml
  greenmask.restore:
    cmds:
      - docker compose -f compose.yml run --rm greenmask restore latest --config /var/lib/workdir/config.yaml
  greenmask.clean:
    cmds:
      - docker compose -f compose.yml run --rm greenmask delete --retain-recent 1 --config /var/lib/workdir/config.yaml
