common:
  pg_bin_path: "/usr/lib/postgresql/16/bin"
  tmp_dir: "/tmp"

storage:
  type: "directory"
  directory:
    path: "/tmp"

dump:
  pg_dump_options:
    jobs: 10

restore:
  insert_error_exclusions:
      global:
        error_codes:
          - "23505"
  pg_restore_options:
    jobs: 10
    inserts: true
    on-conflict-do-nothing: true
    restore-in-order: true
