# Generated by Django 5.0.6 on 2024-06-16 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to='stores')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'db_table': 'stores',
                'ordering': ['-pk'],
                'indexes': [models.Index(fields=['is_verified'], name='stores_is_veri_4d15b2_idx'), models.Index(fields=['website'], name='stores_website_5c8fdb_idx'), models.Index(fields=['author'], name='stores_author__746907_idx')],
            },
        ),
    ]
