# Generated by Django 5.0.6 on 2024-06-16 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('format', models.CharField(choices=[('CODE_128', 'CODE 128'), ('CODABAR', 'CODABAR'), ('QR_CODE', 'QR CODE')], default='CODE_128', max_length=255)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_cards', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_cards', to='stores.store')),
            ],
            options={
                'verbose_name': 'Loyalty card',
                'verbose_name_plural': 'Loyalty cards',
                'db_table': 'loyalty_cards',
                'ordering': ['-pk'],
                'indexes': [models.Index(fields=['is_public'], name='loyalty_car_is_publ_643091_idx'), models.Index(fields=['store'], name='loyalty_car_store_i_c1d629_idx'), models.Index(fields=['author'], name='loyalty_car_author__508cbe_idx')],
            },
        ),
    ]
