name: Release
on:
  release:
    types: [published]
jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: homelab-arc-runner-set
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
      - name: Commit changelog
        run: |
          git checkout dev
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "Update changelog"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git dev
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}
      - name: Update release notes
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          body: ${{ steps.git-cliff.outputs.content }}
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify Slack on Releases
        uses: amendx/slackbot-release@1.0.1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: |
            :tada: *New Release Published* :tada:
            *Repository:* ${{ github.repository }}
            *Tag:* ${{ github.ref_name }}

            *Release Notes:*
            ${{ steps.git-cliff.outputs.content }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
