name: SonarCloud
on:
  push:
    branches:
      - main
      - dev
jobs:
  sonarcloud:
    name: SonarCloud
    env:
      ENVIRONMENT: "demo"
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          version: 1.8.2
          installer-parallel: true
      - name: Install dependencies
        run: poetry -C backend install --with test
      - name: Test for coverage
        run: poetry -C backend run coverage run --rcfile=./backend/pyproject.toml backend/manage.py test backend &&
          poetry -C backend run coverage xml --rcfile=./backend/pyproject.toml
      - name: Upload coverage to Codecov
        run: echo $PWD
      - name: SonarCloud Scan
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: https://sonarcloud.io
        run: docker run --rm -v ./:/usr/src -e SONAR_TOKEN -e SONAR_HOST_URL -e ENVIRONMENT -e GITHUB_TOKEN -e GITHUB_REPOSITORY -e GITHUB_WORKSPACE sonarsource/sonar-scanner-cli
