name: SonarCloud
on:
  push:
    branches:
      - check/sonarqube
      - dev
jobs:
  sonarcloud:
    name: SonarCloud
    env:
      ENVIRONMENT: "demo"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          version: 1.8.2
          installer-parallel: true
      - name: Install dependencies
        run: poetry -C backend install --with test
      - name: Test for coverage
        run: poetry -C backend run coverage run --rcfile=./backend/pyproject.toml backend/manage.py test backend &&
          poetry -C backend run coverage xml --rcfile=./backend/pyproject.toml
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.exclusions=docs/**
            -Dsonar.python.coverage.reportPaths=coverage.xml
