name: SonarCloud
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: self-hosted
    services:
      postgres:
        image: postgres:alpine3.20
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: valkey/valkey:alpine3.20
        ports:
          - 6379:6379
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Set up uv
        # Install latest uv version using the installer
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install dependencies
        working-directory: backend
        run: uv sync --extra test
      - name: Test for coverage
        working-directory: backend
        run: |
          uv run coverage run  manage.py test &&
          uv run coverage xml
        env:
          REDIS_URL: redis://localhost:6379
          PUBLIC_API_SECRET_KEY: ${{ secrets.PUBLIC_API_SECRET_KEY }}
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
          DB_HOST: localhost
          DB_PORT: 5432
      - name: Create docker image
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        run: docker create --name sonar -e SONAR_TOKEN=${SONAR_TOKEN} -e SONAR_HOST_URL=${SONAR_HOST_URL} sonarsource/sonar-scanner-cli
      - name: Add files
        run: docker cp /home/runner/work/loyalist/loyalist/. sonar:/usr/src/.
      - name: Run sonar
        run: docker start -i sonar
      - name: Docker cleanup
        run: |
          docker stop sonar
          docker rm sonar
          docker system prune -f
