name: Run backend tests
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  tests-be:
    runs-on: homelab-arc-runner-set
    env:
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_DB: test
      POSTGRES_PASSWORD: YouShallNotPass
      POSTGRES_USER: appuser
    defaults:
      run:
        working-directory: ./backend
    container: python:3.13-slim
    services:
      postgres:
        env:
          DB_HOST: postgres
          DB_PORT: 5432
          POSTGRES_DB: test
          POSTGRES_PASSWORD: YouShallNotPass
          POSTGRES_USER: appuser
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Python 3.11
        uses: actions/setup-python@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies with uv
        run: uv sync --all-extras
      - name: Run ruff linter
        run: python manage.py test
